### ISSUE TITLE
The Bintray repository is not synced with maven central

### ISSUE THREAD

**Issue by jspare-projects** [jspare-projects/jspare-container#2]
Invalid POM: /org/jspare/jspare-parent/1.0.0/jspare-parent-1.0.0.pom: 
Missing Signature: '/org/jspare/jspare-core/1.0.0/jspare-core-1.0.0-sources.jar.asc' does not exist for 'jspare-core-1.0.0-sources.jar'. 
Missing Signature: '/org/jspare/jspare-core/1.0.0/jspare-core-1.0.0.pom.asc' does not exist for 'jspare-core-1.0.0.pom'.
Missing Signature: '/org/jspare/jspare-core/1.0.0/jspare-core-1.0.0.jar.asc' does not exist for 'jspare-core-1.0.0.jar'.
Missing Signature: '/org/jspare/jspare-parent/1.0.0/jspare-parent-1.0.0.pom.asc' does not exist for 'jspare-parent-1.0.0.pom'.
 Dropping existing partial staging repository.

**Comment by pflima92** [comment]
Resolved with commit 7bb77ce59f7c68aabd55d7ad7f94718028ac4f1d
